### ISSUE TITLE
Watertight check with Trimesh

### ISSUE THREAD

**Issue by frankshen07** [hjwdzh/ManifoldPlus#6]
Hi there, 

Thank you for the great work! I'm using it for my research and I load the processed mesh with trimesh package (in python). However, trimesh shows that the mesh is not watertight (I was checking the results from demo). According to their documentation, 'is_watertight' function checks if a mesh is watertight by making sure every edge is included in two faces. Do you have any insight why this check would fail? Thanks in advance!

**Comment by hjwdzh** [comment]
I actually don't expect it to happen. Would you send me your testing data?

**Comment by frankshen07** [comment]
Thank you for the prompt reply! I was testing with the demo models you provided. The 'broken faces' are in red. Please find the file in test.zip.

[test.zip](https://github.com/hjwdzh/ManifoldPlus/files/4853398/test.zip)

This is the script I run to generate this:
![script](https://user-images.githubusercontent.com/13207197/86155500-7b22d400-bad2-11ea-931f-aba13d219cc6.png)

**Comment by hjwdzh** [comment]
I just took a look at the testing model. I guess the issue is that trimesh automatically merge vertices which are very close to each other, and such merging breaks the watertightness. For example, I opened your mesh in meshlab and it reports identical vertex coordinate. If you did not see that from the direct output from my algorithm, then my guess is highly possible to be true.

**Comment by frankshen07** [comment]
Right, I looked into the trimesh loader and I found there was a flag for automatic post-processing on mesh. If I set that flag to false, the loaded mesh is watertight. Thank you very much for you help!

**Comment by jason718** [comment]
use ```trimesh.load('name.obj', process=False)```
